### ISSUE TITLE
[REFACTOR] Read Dataset from Geochart

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geochart#50]
At the moment, the Geochart plugin get the dataset directly from its configuration. The parsing is done by the GeoView-Geochart. We need to bring the reading inside Geochart so we can, without a map, create and array of charts selectable by the features drop down the same way a click on a map brings many chart.

Use the Airborne Radioactivity layer: https://search.open.canada.ca/openmap/21b821cf-0f1c-40ee-8925-eab12d357668

**Comment by Alex-NRCan** [comment]
I've moved the code to query a url from GeoView-GeoChart to GeoChart component.
